-- 코드를 입력하세요
SELECT A.product_code, price*SUM(sales_amount) AS SALES
FROM PRODUCT A, OFFLINE_SALE B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE;

# SELECT  A.product_code, A.PRICE 
# FROM PRODUCT A, OFFLINE_SALE B
# WHERE A.PRODUCT_ID = B.PRODUCT_ID
# ORDER BY A.PRODUCT_CODE;